### ISSUE TITLE
Use cleaner history

### ISSUE THREAD

**Issue by haarg** [kenahoo/Perl-Parse-CSV#1]
You might want to rebase the history on https://github.com/TheOpenRepository/Parse-CSV, which is a cleaned up version of the SVN repo.

**Comment by kenahoo** [comment]
Thanks, will do.

**Comment by kenahoo** [comment]
I pushed a rebase on top of the new repo.  Not sure how to get it to show up in the Network graph without deleting the repo & cloning from scratch though.  Also not sure if that matters.

**Comment by haarg** [comment]
I don't think it's important to have it showing as a clone, especially since things in TheOpenRepository aren't meant to ever get new commits.
