### ISSUE TITLE
Parse::CSV::Colnames broken

### ISSUE THREAD

**Issue by Tux** [kenahoo/Perl-Parse-CSV#2]
When I test Text::CSV_XS, I also test downriver: I test all modules that (indirectly) require or use Text::CSV_XS.

Since recently, Parse::CSV::Columns started failing, and as this module doen not use Text::CSV_XS directly, but depends on Parse::CSV, I bet you broke their expectations.

Reading what the failing tests expect, this is not what I would expect from Text::CSV_XS, so it must be (have been) a different default behavior for Parse::CSV

If you deliberately broke their expectations (no problem with me on that, you'll probably had a good reason to), I will remove Parse::CSV::Colnames from my checklist

**Comment by kenahoo** [comment]
I didn't deliberately change any behavior, I can check out the failure.  Does it still succeed with the previous Parse::CSV?

**Comment by Tux** [comment]
On Fri, 10 Jul 2015 05:46:35 -0700, Ken Williams
notifications@github.com wrote:

> I didn't deliberately change any behavior, I can check out the failure.
> Does it still succeed with the previous Parse::CSV?

Yes, it does:

$ perl -MV=Parse::CSV
Parse::CSV
        /pro/lib/perl5/site_perl/5.22.0/Parse/CSV.pm: 2.00
$ make test
cp lib/Parse/CSV/Colnames.pm blib/lib/Parse/CSV/Colnames.pm
PERL_DL_NONLAZY=1 "/pro/bin/perl5.22.0" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef _Test::Harness::Switches; test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/_.t
t/01_compile.t .. ok
t/02_main.t ..... ok
t/99_author.t ... skipped: Author tests not required for installation
All tests successful.
Files=3, Tests=61,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.09 cusr  0.00 csys =  0.12 CPU)
Result: PASS

## 

H.Merijn Brand  http://tux.nl   Perl Monger  http://amsterdam.pm.org/
using perl5.00307 .. 5.21   porting perl5 on HP-UX, AIX, and openSUSE
http://mirrors.develooper.com/hpux/        http://www.test-smoke.org/
http://qa.perl.org   http://www.goldmark.org/jeff/stupid-disclaimers/

**Comment by kenahoo** [comment]
I found & fixed the problem - will have a new release in the morning, I hope.

**Comment by Tux** [comment]
(in)direct river-tests++
Thanks for being responsive and reactive

**Comment by kenahoo** [comment]
Released to CPAN - it was relying on some behavior that I think shouldn't be trusted, but I restored it.
